main: me.jasonhorkles.simplebooks.SimpleBooks
name: SimpleBooks
description: A simple plugin to store books and retrieve them with a small command
version: %VERSION%
author: JasonHorkles
website: https://github.com/SilverstoneMC/SimpleBooks
api-version: 1.16

commands:
  forcebook:
    description: "Force a book to be opened at a player"
    permission: simplebooks.force
    usage: "§cUsage: /forcebook <bookname> <player>"
  listbooks:
    description: "List the available book names"
    permission: simplebooks.list
  loadbook:
    description: "Load a saved book"
    permission: simplebooks.load
    usage: "§cUsage: /loadbook <bookname> [player]"
  savebook:
    description: "Save the book you're currently holding"
    permission: simplebooks.save
    usage: "§cUsage: /savebook <bookname>"
  sbrl:
    aliases: [ simplebooksrl, simplebooksreload, sbreload ]
    description: "Reload the plugin"
    permission: simplebooks.reload

permissions:
  simplebooks.force:
    default: op
  simplebooks.list:
    default: op
  simplebooks.load:
    default: op
  simplebooks.reload:
    default: op
  simplebooks.save:
    default: op
